# Generated by Django 5.1.6 on 2025-02-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
